version: "3"

services:
  db:
    image: postgres
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: docker/app/app.dockerfile
    env_file:
      - .env
      - weatherbit.env
    volumes:
      - .:/app
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db